{"name": "test_login_01", "status": "broken", "statusDetails": {"message": "TypeError: 'tuple' object is not callable", "trace": "self = <test_login.TestLogin object at 0x114b84a58>, get_data = ('http://192.168.3.21:30236', ['/account/profile/', '/auth/login/'])\n\n    @allure.feature('登录')\n    @allure.severity('blocker')\n    @allure.story('正常用例-登录成功')\n    # @pytest.mark.parametrize(\"data1,\", [(\"10086\", \"10086\"),] )\n    def test_login_01(self,get_data):\n        \"\"\"\n            用例描述：login成功接口\n        \"\"\"\n        print(\"aa\")\n>       aa,vv=get_data()\nE       TypeError: 'tuple' object is not callable\n\nTestCase/test_login.py:32: TypeError"}, "description": "\n            用例描述：login成功接口\n        ", "start": 1605857438871, "stop": 1605857438871, "uuid": "255589c1-74cf-4de7-9a52-1d79aa73eea1", "historyId": "ad46b58c6f38a9e8de6b92b522c7cbff", "testCaseId": "49d28fbbfb79bd9a490d1da4fd8fe957", "fullName": "TestCase.test_login.TestLogin#test_login_01", "labels": [{"name": "story", "value": "正常用例-登录成功"}, {"name": "feature", "value": "登录"}, {"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Lettos-iMac.local"}, {"name": "thread", "value": "48762-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_login"}]}